language: python
cache: pip

dist: xenial
python: 3.7

branches: {only: [master]}

before_install: pip install -U pipenv
install: pipenv install --system
script: make publish

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: output
  on:
    branch: master