language: node_js
node_js: "12"

branches: {only: [src]}

script: yarn build

cache:
  yarn: true
  directories:
    - node_modules

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: src/.vuepress/dist
  target_branch: master
  fqdn: mileslucas.com
  on:
    branch: src